config/routes.rb
Rails.application.routes.draw do
  root 'tools#index'

  get 'tools/mines'

  get 'tools/cart'

  resource :calendars do
  	post :up_year, :down_year, :up_season, :down_season
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
end

app/models/cs_random.rb
# Stardew Valley utilizes the C# pseudorandom number generator (PRNG)
# PRNG returns the exact same results every time, allowing the user to predict "random" events that occur in the game
# This may change in future versions of the game

class CsRandom < ApplicationRecord
	attr_accessor :seed, :inext, :inextp, :seed_array

	# Constants
	INT_MIN = -2147483648
	INT_MAX = 2147483647
	MBIG = INT_MAX
	MSEED = 161803398
	
	def initialize(seed)
		@seed_array = []

	  subtraction = (seed == INT_MIN) ? INT_MAX : seed.abs
	  mj = MSEED - subtraction
	  seed_array[55] = mj
	  mk = 1

	  (1..54).each do |i|
	  	ii = (21 * i) % 55
	  	seed_array[ii] = mk
	  	mk = mj - mk
	  	mk += MBIG if mk < 0
	  	mj = seed_array[ii]
	  end

	  (1..4).each do |k|
	  	(1..55).each do |i|
	  		seed_array[i] -= seed_array[1 + (i + 30) % 55]
	  		seed_array[i] += MBIG if seed_array[i] < 0
	  	end
	  end

		@seed = seed
	  @inext = 0
	  @inextp = 21
	end

	def sample
		internal_sample * ( 1.0 / MBIG )
	end

	def internal_sample
		locINext = @inext
		locINextp = @inextp

		locINext += 1
		locINextp += 1

		if locINext >= 56
			locINext = 1
		end

		if locINextp >= 56
			locINextp = 1 
		end

		return_value = seed_array[locINext] - seed_array[locINextp]

		if return_value == MBIG
			return_value -= 1
		end

		if return_value < 0
			return_value += MBIG
		end

		seed_array[locINext] = return_value

		@inext = locINext
		@inextp = locINextp

		return_value
	end

	# def get_sample_for_large_range
	# 	result = internal_sample
	# 	if internal_sample % 2 === 0
	# 		result = -result
	# 	end

	# 	d = result
	# 	d += (INT_MAX - 1)
	# 	d /= 2 * INT_MAX - 1
	# 	d
	# end

	def next(*args)
		a, b = *args
		min = 0
		max = INT_MAX

		if b.is_a? Integer
			raise ArgumentError, "Argument out of range" if a > b
			max = b
			min = a if a.is_a? Integer

			range = max - min
			if range <= INT_MAX
				(sample * range + min).to_i 
			else
				#get_sample_for_large_range * range + min
			end
		elsif a.is_a? Integer
			raise ArgumentError, "Argument out of range" if a < 0
			max = a
			(sample * max).to_i 
		else
			internal_sample
		end
	end

	def next_double
		sample
	end
end

app/models/furniture.rb
class Furniture < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
	def up_year
		calendar = Calendar.first
		calendar.day += 112
		calendar.save!
		redirect_back fallback_location: root_path
	end

	def down_year
		calendar = Calendar.first
		calendar.day -= 112
		calendar.save!
		redirect_back fallback_location: root_path
	end

	def up_season
		calendar = Calendar.first
		calendar.day += 28
		calendar.save!
		redirect_back fallback_location: root_path
	end

	def down_season
		calendar = Calendar.first
		calendar.day -= 28
		calendar.save!
		redirect_back fallback_location: root_path
	end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  def index
  end

  def mines
    @calendar = Calendar.first
    if @calendar.day % 28 != 1
      @calendar.day -= (@calendar.day % 28 - 1)
    end
  	# # Temporary Numbers for testing
  	@game_id = 123456789
  end

  def cart
    @calendar = Calendar.first
    if @calendar.day % 28 != 1
      @calendar.day -= (@calendar.day % 28 - 1)
    end
    # Temporary Numbers for testing
    @game_id = 173578236
  end

  def grange

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
	def year(day)
		1 + day / 112
	end

	def season(day)
		case day % 112
		when 1..28
			"Spring"
		when 29..56
			"Summer"
		when 57..84
			"Fall"
		else
			"Winter"
		end
	end
end

app/helpers/tools_helper.rb
module ToolsHelper
	def elevator
		levels = []
		(1..24).each do |n|
			levels << n * 5
		end
		levels
	end

	def override
		levels = []
		(1..120).each do |level|
			if !(level % 40 > 5 && level % 40 < 30 && level % 40 != 19)
				levels << level
			end
		end
		levels
	end

	def monster(game_id, day)
		monster = []
		(1..119).each do |level|
			unless (elevator.include? level) || (override.include? level)
	  		rng = CsRandom.new(day + level + game_id / 2)
	  		monster << level if rng.next_double < 0.05 && rng.next_double < 0.5
	  	end
	  end
	  monster
	end

	def slime(game_id, day)
		slime = []
		(1..119).each do |level|
			unless (elevator.include? level) || (override.include? level)
	  		rng = CsRandom.new(day + level + game_id / 2)
	  		slime << level if rng.next_double < 0.05 && rng.next_double >= 0.5
	  	end
	  end
	  slime
	end

	def mushroom(game_id, day)
		mushroom = []
		(81..119).each do |level|
			unless elevator.include? level
				rng = CsRandom.new(day + level + game_id / 2)
				rng.next_double if rng.next_double < 0.3
				rng.next_double
				mushroom << level if rng.next_double < 0.035
			end
		end
		mushroom
	end

	def cart_stock(game_id, day)
		stock = []
		items = Item.all

		# Cart only shows up on Fridays and Sundays
		if day % 7 == 5 || day % 7 == 0
			rng = CsRandom.new(game_id + day)
			# 10 Normal Item Slots
			(1..10).each do |i|
				item_info = []
				item_key = rng.next(2, 790)
				loop do
					loop do
						item_key = (item_key + 1) % 790
						break if !(off_limits_for_sale.include? item_key) && (Item.find_by item_key: item_key)
					end
					str_array = Item.find_by(item_key: item_key).information.split('/')
					break unless !(str_array[3].include? "-") || (str_array[1].to_i <= 0) || (str_array[3].include? "-13") || (str_array[3] == "Quest") || (str_array[0] == "Weeds") || (str_array[3].include? "Minerals") || (str_array[3].include? "Arch")
				end
				str_array = Item.find_by(item_key: item_key).information.split('/')
				item_info << get_item_name(item_key) #Item Name
				item_info << [rng.next(1, 11) * 100, str_array[1].to_i * rng.next(3, 6)].max #Item Price
				item_info << (rng.next_double < 0.1 ? 5 : 1) # Item Stock
				stock << item_info
			end

			# One Random Furniture
			furniture_info = []
			furniture_key = 0
			loop do
				furniture_key = rng.next(0, 1613)
				break if !(furniture_off_limits_for_sale.include? furniture_key) && (Furniture.find_by furniture_key: furniture_key)
			end
			str_array = Furniture.find_by(furniture_key: furniture_key).information.split('/')
			furniture_info << str_array[0]
			furniture_info << rng.next(1,11) * 250
			furniture_info << 1
			stock << furniture_info

			# Rare Seeds appear in the Spring/Summer
			if season(day) == "Spring" || season(day) == "Summer"
				item_info = ["Rare Seed", 1000, (rng.next_double < 0.1 ? 5 : 1)]
				stock << item_info
			# Rarecrow has a 40% Chance of appearing in the Fall/Winter
			elsif rng.next_double < 0.4
				item_info = ["Rarecrow (4 of 8)", 4000, 1]			
				stock << item_info
			end

			# Coffee Beans have a 25% Chance of appearing all year
			if rng.next_double < 0.25
				item_info = ["Cofee Bean", 2500, 1]
				stock << item_info
			end
		end
		stock
	end

	def get_item_name(item_key)
		str_array = Item.find_by(item_key: item_key).information.split('/')
		str_array[0]
	end


	def off_limits_for_sale
    [680, 681, 682, 688, 689, 690, 774, 775, 454, 460, 645, 413, 437, 439, 158, 159, 160, 161, 162, 163, 326, 341]
  end

  def furniture_off_limits_for_sale
  	[1680, 1733, 1669, 1671, 1541, 1545, 1554, 1402, 1466, 1468, 131, 1226, 1298, 1299, 1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stardew Toolkit</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Mines", tools_mines_path %></li>
        <li><%= link_to "Cart", tools_cart_path %></li>
      </ul>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tools/_floors.html.erb
<%= day + 1 %><br />
Monster: <%= monster(@game_id, day + @calendar.day) == [] ? "None" : monster(@game_id, day + @calendar.day).join(", ") %><br />
Slime: <%= slime(@game_id, day + @calendar.day) == [] ? "None" : slime(@game_id, day + @calendar.day).join(", ") %><br />
Mushroom: <%= mushroom(@game_id, day + @calendar.day) == [] ? "None" : mushroom(@game_id, day + @calendar.day).join(", ") %><br />

app/views/tools/_stock.html.erb
Day: <%= day %><br />
<% cart_stock(@game_id, day + @calendar.day - 1).each do |item_info| %>
	<%= item_info[0] %> x <%= item_info[2] %> - <%= item_info[1] %>g<br />
<% end %>

app/views/tools/cart.html.erb
<h1>Traveling Merchant Stock</h1>
<p>Finds the Merchant Stock</p>
<%= @calendar.day %>
<p>
	<div class="row">
    <div class="col-md-12">
      <table class="table-bordered table-striped">
        <thead>
          <tr>
            <th colspan="7" class="text-center">
              <% if @calendar.day > 112 %>
                <%= link_to " ", down_year_calendars_path, :method=> :post, class: 'glyphicon glyphicon-chevron-left text-right' %>
              <% end %>
            	<span>Year <%= year(@calendar.day) %></span>
              <%= link_to " ", up_year_calendars_path, :method=> :post, class: 'glyphicon glyphicon-chevron-right text-left' %>
            </th>
          </tr>
          <tr>
            <th colspan="7" class="text-center">
              <% if @calendar.day > 28 %>
                <%= link_to " ", down_season_calendars_path, :method=> :post, class: 'glyphicon glyphicon-chevron-left text-right' %>
              <% end %>
              <span><%= season(@calendar.day) %></span>    
              <%= link_to " ", up_season_calendars_path, :method=> :post, class: 'glyphicon glyphicon-chevron-right text-left' %>
            </th>
          </tr>
          <tr>
            <th class="col-md-1">Week</th>
            <th class="col-md-3">Friday</th>
            <th class="col-md-3">Sunday</th>
          </tr>
        </thead>
        <tbody>
          <% [5, 7, 12, 14, 19, 21, 26, 28].each do |day| %>
            <% if day % 7 == 5 %>
              <tr><th>Week <%= day / 7 + 1 %>
            <% end %>
              <th><%= render partial: 'tools/stock', locals: {game_id: @game_id, day: day} %></th>
            <% if day % 7 == 6 %>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
	</div>
</p>

app/views/tools/index.html.erb
<h1>Home</h1>
<p><%= link_to "Mines", tools_mines_path %></p>
<p><%= link_to "Traveling Merchant", tools_cart_path %></p>

app/views/tools/mines.html.erb
<h1>Mines</h1>
<p>Finds the special floors in the mines</p>
<%= @calendar.day %>
<p>
	<div class="row">
    <div class="col-md-12">
      <table class="table-bordered table-striped">
        <thead>
          <tr>
            <th colspan="7" class="text-center">
              <% if @calendar.day > 112 %>
                <%= link_to " ", down_year_calendars_path, :method=> :post, class: 'glyphicon glyphicon-chevron-left text-right' %>
              <% end %>
            	<span>Year <%= year(@calendar.day) %></span>
              <%= link_to " ", up_year_calendars_path, :method=> :post, class: 'glyphicon glyphicon-chevron-right text-left' %>
            </th>
          </tr>
          <tr>
            <th colspan="7" class="text-center">
              <% if @calendar.day > 28 %>
                <%= link_to " ", down_season_calendars_path, :method=> :post, class: 'glyphicon glyphicon-chevron-left text-right' %>
              <% end %>
              <span><%= season(@calendar.day) %></span>    
              <%= link_to " ", up_season_calendars_path, :method=> :post, class: 'glyphicon glyphicon-chevron-right text-left' %>
            </th>
          </tr>
          <tr>
            <th class="col-md-1">Mo</th>
            <th class="col-md-1">Tu</th>
            <th class="col-md-1">We</th>
            <th class="col-md-1">Th</th>
            <th class="col-md-1">Fr</th>
            <th class="col-md-1">Sa</th>
            <th class="col-md-1">Su</th>
          </tr>
        </thead>
        <tbody>
          <% (1..28).each do |day| %>
            <% if day % 7 == 1 %>
              <tr>
            <% end %>
              <th><%= render partial: 'tools/floors', locals: {game_id: @game_id, day: day} %></th>
            <% if day % 7 == 0 %>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
	</div>
</p>